language: nix
git:
  quiet: true
  depth: 3

# follows https://nvie.com/posts/a-successful-git-branching-model
branches:
  only:
    - master
    - develop
    - - /^release-.*$/
    - - /^feature-.*$/
    - - /^hotfix-.*$/
    - 2019-09-12_travis-ci

# allows plenty of time to save the nix store before the actual timeout:
script: timeout 120 ./test.sh

# follows https://nixos.wiki/wiki/Nix_on_Travis
# TODO how best to cache the nix-shell stuff?
cache:
  directories:
    - $HOME/nix.store
before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store $(readlink result)
before_script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

# probably overkill because nixpkgs/default.nix already pins it, but can't hurt
# follows https://github.com/travis-ci/docs-travis-ci-com/issues/2236
env:
  - NIX_PATH=nixpkgs=channel:nixos-19.03
