language: nix
nix: 2.3

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: xenial
    env: NIX_PATH=nixpkgs=channel:nixos-19.03
  - os: osx
    osx_image: xcode10.1
    env: NIX_PATH=nixpkgs=channel:nixpkgs-19.03-darwin

git:
  # quiet: true
  depth: 1

# see: https://nvie.com/posts/a-successful-git-branching-model
branches:
  only:
  - master
  - develop
  - /^module-.*$/
  - /^release-.*$/
  - /^feature-.*$/
  - /^hotfix-.*$/

script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use jefdaj || sudo cachix use jefdaj
  - ./test.sh || cat /tmp/shortcut.log

notifications:
  email:
  on_success: change
  on_failure: change
