language: nix
script: ./test.sh
git:
  quiet: true
  depth: 3

# attempting to follow https://nvie.com/posts/a-successful-git-branching-model
branches:
  only:
    - master
    - develop
    - 2019-09-12_travis-ci
