flags: {}
nix:
  enable: true
  pure: false
extra-package-dbs: []
packages:
- .

# it works best if this matches the haskell.compiler.ghcXXX version in default.nix
system-ghc: true
resolver: lts-12.26
extra-deps:
- posix-escape-0.1
- shake-0.17.5
ghc-options:
        # "$everything": -no-rtsopts
        # "$targets": -Werror
        "$everything": -threaded -rtsopts -Wall -Wno-orphans -O2 "-with-rtsopts=-N -IO"
