flags: {}
allow-newer: true

# this seems to fix the zlib bug in stack repl for now, but it's fiddly
# see: https://github.com/commercialhaskell/stack/issues/2130#issuecomment-247032332
# uncomment the packages: line to get stack repl to work:
# nix-shell --command 'stack repl' (or similar)
# ...but take it away to get regular builds to work
nix:
  enable: true
  # packages: [zlib.dev, zlib.out, pkgconfig, haskell.compiler.ghc865]

extra-package-dbs: []
packages:
- .
- logging

# it works best if this matches the haskell.compiler.ghcXXX version in default.nix
system-ghc: true
resolver: lts-14.4
extra-deps:
  - posix-escape-0.1
  - path-io-1.6.0
  - progress-meter-1.0.0.1

# TODO are the rtsopts a problem? see if removing fixes any fails
ghc-options:
        # "all": -O2
        # "OrthoLang": -O0
