# since ortholang requires lots of nix dependencies, the simplest way to
# integrate with stack appears to be manually using a nix-shell, like this:
#
# nix-shell --run 'stack repl; exit'
#
# therefore, nix is disabled below

flags: {}
allow-newer: true

nix:
  enable: false

extra-package-dbs: []
packages:
- .

# it works best if the expected compiler matches myGHC in default.nix
system-ghc: true
resolver: lts-16.18
extra-deps:
  - progress-meter-1.0.0.1
  - posix-escape-0.1
  - download-0.3.2.7
  - store-0.7.4
  - store-core-0.4.4.2
  - th-utilities-0.2.4.0
  - MissingH-1.4.3.0
  - github: jefdaj/docopt.hs
    commit: 080c3ba6badd736f1b4a3f1f13dbd4c107614136
  - github: jefdaj/logging
    commit: c73b189e083a6427ef5c3e02c0e2fc8387df8382

build:
  haddock: true
