flags: {}
nix:
  enable: true
  pure: false
extra-package-dbs: []
packages:
- .
resolver: lts-11.22
extra-deps:
- Command-0.0.7
- posix-escape-0.1
# ghc-options:
#     "$targets": -Werror
#     "$everything": -O2 -N -IO
