flags: {}
allow-newer: true

# this seems to fix the zlib bug in stack repl for now, but it's fiddly
# see: https://github.com/commercialhaskell/stack/issues/2130#issuecomment-247032332
# uncomment the packages: line to get stack repl to work:
# nix-shell --command 'stack repl' (or similar)
# ...but take it away to get regular builds to work
nix:
  enable: true
  pure: false
  packages: [zlib.dev, zlib.out, pkgconfig, haskell.compiler.ghc883]

extra-package-dbs: []
packages:
- .
- logging
- docopt

# it works best if this matches the haskell.compiler.ghcXXX version in default.nix
# lts-15.10 = ghc883
# lts-14.27 = ghc865
system-ghc: true
resolver: lts-15.10
extra-deps:
  - progress-meter-1.0.0.1
  - posix-escape-0.1
  - download-0.3.2.7
  - store-0.7.4
  - store-core-0.4.4.2
  - th-utilities-0.2.4.0
  - MissingH-1.4.3.0
  # - path-io-1.6.0

build:
  haddock: true
