# TODO load all the nix dependencies in here, including the scripts?

resolver: lts-8.6
packages:
- '.'
- 'shake'
extra-deps:
- Command-0.0.7
flags: {}
extra-package-dbs: []
nix:
  enable: true
  pure: false
