flags: {}
nix:
  enable: true
  pure: false
extra-package-dbs: []
packages:
- .
extra-deps:
- Command-0.0.7
- concurrent-extra-0.7.0.12
- lock-file-0.5.0.2
- posix-escape-0.1
- tagged-exception-core-2.2.0.0
resolver: lts-9.5
